apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure-parent
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@gitlab.com:yairdamri48-group/argocd-project.git'
    targetRevision: HEAD
    path: infrastructure/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
