
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-community-operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://mongodb.github.io/helm-charts'
    chart: community-operator
    targetRevision: "0.13.0"
    helm:
      parameters: 
      - name: installCRDs
        value: true
      - name: watchNamespaces[0]
        value: "demo-crm"
      - name: watchNamespace
        value: "*"
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-crm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
