apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-cluster
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://gitlab.com/yair_portfolio/workout-gen.git
    targetRevision: HEAD
    path: k8s/charts/manifests/mongodb
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: workout
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
