apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workout-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: git@gitlab.com:yair_portfolio/k8s-infra.git
    targetRevision: HEAD
    path: k8s/charts/workout-stack
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: workout
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
