apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging
  namespace: argocd
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: "git@gitlab.com:yair_portfolio/argocd-gitops.git"
    targetRevision: HEAD
    path: infra/logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
        - CreateNamespace=true