---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCZDShYJpSsF3jxzbnMcTLTxqNmtvnIafER/s5hTgsvsn7nK/bgcpowGOQGx5NZn2hbAXbeV0uslTmK6gEDme5yrJUfcX2ZRper7PMZspsAJTOoCfrt6D/8XviZ8ke3P0hi4ysZ6ZBOY00kbHqG0eLjJN/KCaQPmiy1VYTRWkGHkKwJYXyOWjeQVCABqooOWTSoxp5LwEm7V/dH2Mc5t4K5GoHra37I7zvoxvp9YijPcZ2xvBtkZUmAB6i2Iz4rDzL7oJ3JrMpKBLUWTMaC/mUtilXiLvEfe+jSINBS2yVMPjmtape3/JOSHvosMAfA8irhBv7Dnh5fWmCAh8SIy+TcXA/K+k+ml+wOdZ0HV9EzIgnWC66hYMaqnzchdKWjqcvnm3uVXyK3Zy7d+Y9drdG2KXjPvaxN2A+e/zeFUqryi47ZPSMuuTR9kr2oHH3QDA8x49l/jwrgcnxnShrwqNTyF+F7cb80LMdoyHANoCvnJcKZuUqob1tmUr804saBm0NCGDx9ZxATom94YdMDQ7PF+trSh35rVrbFjErvnctAfFSf8/nPL3LOtGrA6bUh8k8LmLx7wdWnf+xZXl76Z8GWQNJs0kxcr3C8z+tXZGNWS14X2vAbVrQK327r2l5UCkTJ3y9sO+9sfABiLHuBdwjscGe8Kz5ZQdRUy0pW6fz/aKdU24368hfUtDn3CyfZg3oIKdeJ1T3l1dRX
    admin-user: AgBwbPC3uXKcq8gcoPqn2y2AHDDR7X+WC/UfZZAf9I9TlFe4tuTGxnxiZcxgnZtJJEJ2eaNnfJo5lA5LWVFTnIutDAU9J8jslW0eF4zh1aW+Zms/JBCJNlY8Em2527Pe9rkuL0NjjLEA81bwKX13fVel6aHfBbiExw35XHkCqXkUTl1UCHRpU6VZAcT16QZ7XQCru8br3c/2NJ9cqnS6S999536d4nsiu1AgKid6448kGQ9X1d86Ef8T2J77XYrY4Aqu9kWB2CTTz1EIoOl2vWQ+NQXfyGuev3xX5OVdfNz+fcYh6poYMkWA61Tf2oXErVoHFx3NGVtCL4mB2SROMIz0v3jJ0DI46MldCY2IgmIaFrKg3xbtXZaUV6X7jQHPa30KHUR0dGD4a7lsb8l0RtF3LnVHebWYoxiUCon8xX+Cs4Pa+pLk9fACO+agBCxoYywI0ZS0IzZj/kcsPAU04vhBiFnYTle4J7keqoGvg2hMfUKWLb6XvhOMxv3ZTPXHLG90JN6ugK+/XbAsIq/l+JDpc7VJUQu0xmoyyIQZHWbbLey7FqhBg8/ud+zzsyNIoUObyy+gJKKJ2rmFUKoCPwaaADJek0+FbtHzhU68Gj+9lRqZV7y3ufbCUUlcEHxxGooaSWSxYgXcs3PMncxPoEbV2qwK6fFXTIptlXrHhY1eDYvUaqxHLXc90u+qnF0r67rm/GTwkA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring
