apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: efk-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: logging
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: git@gitlab.com:yair_portfolio/argocd-gitops.git
    targetRevision: HEAD
    path: argocd/infra/logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
