# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: infra-sealed-secrets
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://bitnami-labs.github.io/sealed-secrets
#     chart: sealed-secrets
#     targetRevision: 2.17.7
#     helm:
#       releaseName: sealed-secrets
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: sealed-secrets
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
#       - PrunePropagationPolicy=foreground
#       - PruneLast=true
#   revisionHistoryLimit: 10
