apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticsearch
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://helm.elastic.co
    chart: elasticsearch
    targetRevision: 7.17.3
    helm:
      values: |
        replicas: 1
        minimumMasterNodes: 1
        
        # Single-node cluster configuration
        clusterHealthCheckParams: "wait_for_status=yellow&timeout=1s"
        
        # Configure resource limits and requests
        resources:
          requests:
            cpu: "50m"
            memory: "512Mi"
          limits:
            cpu: "250m"
            memory: "1Gi"
            
        # Storage configuration
        volumeClaimTemplate:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 5Gi
          
        # Set appropriate JVM heap size
        esJavaOpts: "-Xmx256m -Xms256m"
        
        # For development/testing environments
        antiAffinity: "soft"
        
  destination:
    server: https://kubernetes.default.svc
    namespace: efk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
