apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.24.0
    helm:
      values: |
        # DaemonSet for collecting logs from all nodes
        kind: DaemonSet
        
        # Configure resource limits
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
            
        # Configure service for metrics
        service:
          extraPorts:
            - name: metrics
              port: 2020
              protocol: TCP
        
        # Configure tolerations to run on all nodes
        tolerations:
          - operator: Exists
        
        # Configure log collection and output
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush 5
                Log_Level info
                Parsers_File parsers.conf
                Parsers_File custom_parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port 2020
                Health_Check On
                storage.path /var/fluent-bit/state/flb-storage/
                storage.sync normal
                storage.checksum off
                storage.max_chunks_up 128
          
          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                multiline.parser docker, cri
                Tag kube.*
                Mem_Buf_Limit 10MB
                Skip_Long_Lines On
                Refresh_Interval 10
                DB /var/fluent-bit/state/flb_kube.db
                DB.Sync Normal
                
          filters: |
            # Kubernetes enrichment
            [FILTER]
                Name kubernetes
                Match kube.*
                Kube_URL https://kubernetes.default.svc:443
                Kube_CA_File /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
                Kube_Token_File /var/run/secrets/kubernetes.io/serviceaccount/token
                Kube_Tag_Prefix kube.var.log.containers.
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude On
                Labels On
                Annotations Off
                
            # Parse JSON logs from application
            [FILTER]
                Name parser
                Match kube.*
                Key_Name log
                Parser json
                Reserve_Data On
                Preserve_Key On
                
            # Nest Kubernetes metadata for cleaner structure
            [FILTER]
                Name nest
                Match kube.*
                Operation lift
                Nested_under kubernetes
                Add_prefix k8s_
                
          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Host elasticsearch-master.efk.svc.cluster.local
                Port 9200
                Logstash_Format On
                Logstash_Prefix kubernetes
                Logstash_DateFormat %Y.%m.%d
                Replace_Dots On
                Retry_Limit False
                Type _doc
                Time_Key @timestamp
                Generate_ID On
                Include_Tag_Key On
                Tag_Key _fluentbit_tag
                Buffer_Size 5MB
                
        # Custom parsers for JSON logs
        customParsers: |
          [PARSER]
              Name json
              Format json
              Time_Key time
              Time_Format %Y-%m-%dT%H:%M:%S.%L%z
              Time_Keep On
              
          [PARSER]
              Name docker
              Format json
              Time_Key time
              Time_Format %Y-%m-%dT%H:%M:%S.%L
              Time_Keep On
        
        # Volume mounts with state persistence
        daemonSetVolumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
          - name: etcmachineid
            hostPath:
              path: /etc/machine-id
              type: File
          - name: flb-storage
            hostPath:
              path: /var/fluent-bit/state
              
        daemonSetVolumeMounts:
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: etcmachineid
            mountPath: /etc/machine-id
            readOnly: true
          - name: flb-storage
            mountPath: /var/fluent-bit/state

  destination:
    server: https://kubernetes.default.svc
    namespace: efk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
