apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluent-bit
    targetRevision: 0.24.0
    helm:
      values: |
        # DaemonSet for collecting logs from all nodes
        kind: DaemonSet
        
        # Configure resource limits - Fluent Bit is much more lightweight
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
            
        # Configure service for metrics
        service:
          extraPorts:
            - name: metrics
              port: 2020
              protocol: TCP
        
        # Configure tolerations to run on all nodes
        tolerations:
          - operator: Exists
        
        # Configure log collection and output
        config:
          service: |
            [SERVICE]
                Daemon Off
                Flush 1
                Log_Level info
                Parsers_File parsers.conf
                HTTP_Server On
                HTTP_Listen 0.0.0.0
                HTTP_Port 2020
                Health_Check On
          
          inputs: |
            [INPUT]
                Name tail
                Path /var/log/containers/*.log
                multiline.parser docker, cri
                Tag kube.*
                Mem_Buf_Limit 5MB
                Skip_Long_Lines On
                
          filters: |
            [FILTER]
                Name kubernetes
                Match kube.*
                Merge_Log On
                Keep_Log Off
                K8S-Logging.Parser On
                K8S-Logging.Exclude On
                
          outputs: |
            [OUTPUT]
                Name es
                Match kube.*
                Host elasticsearch-master.efk.svc.cluster.local
                Port 9200
                Logstash_Format On
                Logstash_Prefix kubernetes
                Replace_Dots On
                Retry_Limit False
                
        # No custom parsers needed, using built-in ones
        
        # Standard volume mounts
        daemonset:
          volumes:
            - name: varlog
              hostPath:
                path: /var/log
            - name: varlibdockercontainers
              hostPath:
                path: /var/lib/docker/containers
            - name: etcmachineid
              hostPath:
                path: /etc/machine-id
                type: File
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: etcmachineid
              mountPath: /etc/machine-id
              readOnly: true

  destination:
    server: https://kubernetes.default.svc
    namespace: efk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
