apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluentd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://fluent.github.io/helm-charts
    chart: fluentd
    targetRevision: 0.3.9
    helm:
      values: |
        # Enable the Kubernetes metadata filter
        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "24231"

        # Configure resources
        resources:
          limits:
            cpu: 100m
            memory: 400Mi
          requests:
            cpu: 50m
            memory: 200Mi
            
        # DaemonSet configuration to collect logs from all nodes
        kind: DaemonSet
        
        # Create custom configurations instead of using configMapConfigs with dots
        # This avoids the invalid volume name issue
        configMaps:
          useDefaults:
            prometheus: true
            containers: true
          
        # Configure output to Elasticsearch
        env:
          - name: FLUENT_ELASTICSEARCH_HOST
            value: "elasticsearch-master.efk.svc.cluster.local"
          - name: FLUENT_ELASTICSEARCH_PORT
            value: "9200"
          - name: FLUENT_ELASTICSEARCH_SCHEME
            value: "http"
          - name: FLUENTD_SYSTEMD_CONF
            value: "disable"
            
        # Mount host paths for log collection
        extraVolumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
              
        extraVolumeMounts:
          - name: varlog
            mountPath: /var/log
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
            
        # Disable PodSecurityPolicy since it's not available in the cluster
        podSecurityPolicy:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: efk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
