apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretstore
  namespace: logging
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        # Use AWS SDK default credentials chain - which will use the node role
        # This works because we attached the external-secrets policy to the node role
        secretsManager: {}

